heat_template_version: 2016-10-14

description: |
  The heat template is used to demo the autoscaling and autohealing for a webserver.
parameters:
  keypair:
    type: string
    default: KEY-NAME
  webserver_image_id:
    description: changed to use ubuntu 18.04.
    type: string
    default: 0da75c8a-787d-48cd-bb74-e979fc5ceb58 # image ID of ubuntu instance on the hamilton region
  webserver_flavor_id:
    type: string
    default: c1.c1r1 # Flavor with 1GB RAM and 10GB disk space
  webserver_network_id:
    type: string
    default: NETWORK-ID
  vip_subnet_id:
    description: Should be a subnet of webserver_network_id
    type: string
    default: SUBNET-ID
  public_network:
    description: Public network name, could get by 'openstack network list --external'
    type: string
    default: public-net

resources:
  security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      rules: [
        {protocol: "tcp", "port_range_min": 80, "port_range_max": 80},
        {protocol: "tcp", "port_range_min": 22, "port_range_max": 22},
      ]
  autoscaling_group:
    type: OS::Heat::AutoScalingGroup
    properties:
      min_size: 2
      max_size: 4
      resource:
        type: OS::LB::Server
        properties:
          keypair: {get_param: keypair}
          flavor_id: {get_param: webserver_flavor_id}
          image_id : {get_param: webserver_image_id}
          network_id: {get_param: webserver_network_id}
          sg_ids: [{get_resource: security_group}]
          public_network: {get_param: public_network}
          pool_id: {get_resource: loadbalancer_pool}
          metadata: {"metering.server_group": {get_param: "OS::stack_id"}}
  loadbalancer:
    type: OS::Octavia::LoadBalancer
    properties:
      vip_subnet: {get_param: vip_subnet_id}
      name: webserver_lb
  loadbalancer_public_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: {get_param: public_network}
      port_id: {get_attr: [loadbalancer, vip_port_id]}
  listener:
    type: OS::Octavia::Listener
    properties:
      name: webserver_listener
      protocol: HTTP
      protocol_port: 80
      loadbalancer: {get_resource: loadbalancer}
  loadbalancer_pool:
    type: OS::Octavia::Pool
    properties:
      lb_algorithm: ROUND_ROBIN
      protocol: HTTP
      listener: {get_resource: listener}
  loadbalancer_healthmonitor:
    type: OS::Octavia::HealthMonitor
    properties:
      delay: 5
      max_retries: 3
      pool: {get_resource: loadbalancer_pool}
      timeout: 15
      type: HTTP
      http_method: GET
      expected_codes: 200


outputs:
  lb_ip:
    value: {get_attr: [loadbalancer_public_ip, floating_ip_address]}
  lb_vip:
    value: {get_attr: [loadbalancer, vip_address]}
