parameters:
  key_name: <insert your key name here>
  image: ubuntu-14.04-x86_64
  servers_flavor: c1.c1r1
  site_name: catcloud
  environment: test
  app_type: moodle
  site_url: moodle-heat.elearning.catalyst.net.nz
  moodle_version: 29
  db_root_password: <insert your DB root password here>

