---

heat_template_version: 2018-08-31

description: |
  The resource definition used to create web server
  cluster members, and add them to the load balancer pool.

parameters:
  keypair:
    type: string
  image:
    type: string
  flavor:
    type: string
  network:
    type: string
  security_groups:
    type: comma_delimited_list
  group:
    type: string
  loadbalancer_pool:
    type: string

resources:
  webserver:
    type: OS::Nova::Server
    properties:
      image: {get_param: image}
      flavor: {get_param: flavor}
      networks:
        - network: {get_param: network}
      key_name: {get_param: keypair}
      security_groups: {get_param: security_groups}
      scheduler_hints:
        group: {get_param: group}
      metadata:
        metering.server_group: {get_param: group}
      config_drive: true
      user_data_format: RAW
      user_data: {get_file: user_data.sh}
  loadbalancer_pool_member:
    type: OS::Octavia::PoolMember
    properties:
      pool: {get_param: loadbalancer_pool}
      address: {get_attr: [webserver, first_address]}
      protocol_port: 80

outputs:
  server_id:
    value: {get_resource: webserver}
